ui: mocha-bdd
browsers:
  - name: ie
    version: '6..latest'
  - name: firefox
    version: '4..latest'
  - name: firefox
    version: beta
  - name: chrome
    version: '26..latest'
  - name: chrome
    version: beta
  - name: opera
    version: '11..latest'
  - name: safari
    version: '5..latest'
  - name: ipad
    version: '5.1..latest'
  - name: iphone
    version: '5.1..latest'
  - name: android
    version: '4.0..latest'
